config/routes.rb
Rails.application.routes.draw do
 mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'posts#index'
  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :galleries do
    member do
      put "like" => "galleries#vote"
    end
  end
  resources :posts do
    resources :comments
    member do
      put "like" => "posts#vote"
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  acts_as_votable
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :content, presence: true, length: { minimum: 5 }
  validates :title, presence: true, length: { minimum: 4 }
  mount_uploader :image, ImageUploader
  default_scope -> { order(updated_at: :desc) }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :vote]
  load_and_authorize_resource

  respond_to :js, :json, :html

  def index
    @posts = Post.paginate(page: params[:page], per_page: 4)
  end

  def show
    # @comments = Comment.all
    @comments = Comment.where(post_id: @post).order("created_at DESC")
    @comments = @post.comments.paginate(page: params[:page], per_page: 3)
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
    end
  end

  def vote
    if !current_user.liked? @post
      @post.liked_by current_user
    elsif current_user.liked? @post
      @post.unliked_by current_user
    end
  end

  private
    def set_post
      @post = Post.friendly.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The page you were looking for could be found!"
      redirect_to(request.referrer || posts_url)
    end

    def post_params
      params.require(:post).permit(:title, :content, :user_id, :image, :slug)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="col-md-4 mx-auto p-top">
  <div class="card grey-gradient white-text">
    <div class="card-block">
      <div class="form-header grey-gradient">
        <i class="fa fa-book fa-2x"></i>
      </div>
        <%= form_for @post, html: { multipart: true } do |f| %>
          <% if post.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

              <ul>
              <% post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="md-form">
            <%= image_tag(@post.image_url) if @post.image? %><br>
            <div class="text-center">
              <i class="fa fa-camera-retro prefix fa-fonts"></i>
              <%= f.file_field :image %>
            </div>
            <%= f.hidden_field :image_cache %>
          </div>

          <div class="md-form">
            <i class="fa fa-tags prefix white-text"></i>
            <%= f.text_field :title, id: :post_title, placeholder: "Enter title", autofocus: true, class: "form-control white-text" %>
          </div>

          <div class="md-form">
            <i class="fa fa-pencil prefix white-text"></i>
            <%= f.text_area :content, id: :post_content, placeholder: "Enter description", class: "md-textarea white-text" %>
          </div>

          <div class="md-form">
            <%= f.button class: "btn btn-block btn-lg btn-rounded btn-outline-white grey-gradient", data: { disable_with: "<i class='fa fa-spinner fa-5x fa-spin'></i>"} %>
          </div>
        <% end %>

    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>


<%= link_to '', :back, class: "fa fa-hand-o-left fa-2x grey-text" %>

app/views/posts/index.html.erb
<br>
<div class="container">
            <!--First row-->
            <div class="row mt-1">

                <!--First column-->
                <div class="col-md-12">

                    <!--Carousel Wrapper-->
                    <div id="carousel-example-3" class="carousel slide carousel-fade z-depth-1-half" data-ride="carousel">
                        <!--Indicators-->
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-example-3" data-slide-to="0" class=""></li>
                            <li data-target="#carousel-example-3" data-slide-to="1" class="active"></li>
                            <li data-target="#carousel-example-3" data-slide-to="2" class=""></li>
                        </ol>
                        <!--/.Indicators-->

                        <!--Slides-->
                        <div class="carousel-inner" role="listbox">
                            <!--First slide-->
                            <div class="carousel-item">
                                <!--Mask color-->
                                <div class="view hm-black-slight">
                                    <img src="https://s3.amazonaws.com/conceptsphotography/uploads/gallery/images/2/DumboDogWalker.jpg" class="img-fluid" alt="">
                                    <div class="full-bg-img">
                                    </div>
                                </div>
                                <!--Caption-->
                                <div class="carousel-caption caption-2">
                                    <div class="animated fadeInDown">
                                        <h2 class="h2-responsive">Amazing month in Indonesian rainforest</h2>
                                    </div>
                                </div>
                                <!--Caption-->
                            </div>
                            <!--/First slide-->

                            <!--Second slide-->
                            <div class="carousel-item active">
                                <!--Mask color-->
                                <div class="view hm-black-slight">
                                    <img src="https://s3.amazonaws.com/conceptsphotography/uploads/gallery/images/2/BrooklynBridge2.jpg" class="img-fluid" alt="">
                                    <div class="full-bg-img">
                                    </div>
                                </div>
                                <!--Caption-->
                                <div class="carousel-caption caption-2">
                                    <div class="animated fadeInDown">
                                        <h2 class="h2-responsive">autumn bike ride around New York City</h2>
                                    </div>
                                </div>
                                <!--Caption-->
                            </div>
                            <!--/Second slide-->

                            <!--Third slide-->
                            <div class="carousel-item">
                                <!--Mask color-->
                                <div class="view hm-black-slight">
                                    <img src="https://s3.amazonaws.com/conceptsphotography/uploads/gallery/images/2/AtlanticAve.jpg" class="img-fluid" alt="">

                                    <div class="full-bg-img">
                                    </div>
                                </div>
                                <!--Caption-->
                                <div class="carousel-caption caption-2">
                                    <div class="animated fadeInDown">
                                        <h2 class="h2-responsive">Photographs from mountain lake</h2>
                                    </div>
                                </div>
                                <!--Caption-->
                            </div>
                            <!--/Third slide-->
                        </div>
                        <!--/Slides-->

                        <!--Controls-->
                        <a class="carousel-control-prev" href="#carousel-example-3" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carousel-example-3" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                        <!--/.Controls-->
                    </div>
                    <!--/Carousel Wrapper-->
                </div>
                <!--/First column-->
            </div>
            <!--First row-->

            <div class="divider-new wow fadeIn" data-wow-delay="0.3s" style="visibility: visible; animation-delay: 0.3s; animation-name: fadeIn;">
                <h2 class="h2-responsive">What's new?</h2>
            </div>
                    <% Post.all.each do |post| %>
                    <div class="row white-text">

                <!--Grid column-->
                <div class="col-lg-5 ml-auto col-xl-4 pb-3">
                    <!--Featured image-->
                    <div class="view overlay hm-white-slight z-depth-1-half">
                        <% if post.image? %>
                            <%= link_to image_tag post.image_url, class: "image-fluid hm-zoom", style: "width: 100%;" if post.image? %>
                        <% else %>
                            <img src="https://www.pfsuites.com/images/no_image_available.png" class="image-fluid hm-zoom" style="width: 100%;" alt="Empty Image">
                        <% end %>
                        <a>
                            <div class="mask waves-effect waves-light"></div>
                        </a>
                    </div>
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-7 mr-auto col-xl-6">
                    <!--Excerpt-->
                    <a href="" class="green-text"><h6 class="font-bold pb-1"><i class="fa fa-tags"></i> Food</h6></a>
                    <h4 class="h4-responsive"><strong><%= link_to(post.title, post_path(post)) %></strong></h4>
                    

                    <p><%= truncate(post.content, escape: false, length: 250) %></p>
                    <p>By <a><strong><%= post.user.full_name.titleize %></strong></a>, <%= post.created_at.strftime("%B %d %Y") %> </p>
                    <p class="fa fa-comments-o"> <span class="badge grey-gradient"> <%= post.comments.count %> </span> </p> &nbsp;
                    <p class="fa fa-heart"> <span class="badge grey-gradient"> <%= post.get_upvotes.size %> </span> </p>
                    <div class="center">
                        <%= link_to 'Read More', post_path(post), class: "btn btn-outline-white grey-gradient mb-3 waves-effect waves-ligh" %>
                    </div>
                </div>
                <!--Grid column-->

            </div>




                    
                    <% end %>
                    
       
        </div>
            <!--Pagination dark grey-->
            <div class="center">
                <div class="page_info white-text">
                    <%= page_entries_info @posts %>
                </div>
                 <%= will_paginate @posts %>
            </div> <br> <br>
            <!--/Pagination dark grey-->
	<div class="center">
	   <%= link_to 'New Post', new_post_path, class: "btn btn-outline-white btn-rounded grey-gradient white-text" %>
	</div>

app/views/posts/new.html.erb
<!-- <h1 class="h1-responsive text-center white-text">New Post</h1> -->

<%= render 'form', post: @post %>

<%= link_to '', posts_path, class: "fa fa-hand-o-left fa-2x grey-text faa-horizontal animated" %>

app/views/posts/show.html.erb
<div class="container white-text">
  <!-- Magazine -->
  <div class="row">
    <!-- Main  -->
    <div class="col-md-12">
      <!-- Section: Single article -->
      <section class="article-section">
        <!-- Image -->
        <div class="view overlay hm-white-light z-depth-2 wow fadeIn" style="visibility: visible; animation-name: fadeIn;">
        <% if @post.image? %>
          <%= image_tag @post.image, class: "img-fluid" %>
        <% else %>
          <img src="https://www.pfsuites.com/images/no_image_available.png" class="image-fluid hm-zoom" style="width: 100%; height: 625px;" alt="Empty Image">
        <% end %>
          <a>
            <div class="mask waves-light waves-effect waves-light"></div>
          </a>
        </div>
        <br>
        <div class="article-text wow fadeIn" data-wow-delay="0.3s" style="visibility: visible; animation-delay: 0.3s; animation-name: fadeIn;">
          <!-- Post data -->
          <h1 class="h1-responsive text-center"><%= @post.title %></h1>

          <h5 class="text-center ">By<a href="" class="white-text"><strong> <%= @post.user.full_name.titleize %></strong></a> on <%= @post.created_at.strftime("%B  %d %Y") %> &nbsp; &nbsp; &nbsp;

          <div class="section-heading">
          <br>
            <%= link_to like_post_path(@post), class: "like-btn", method: :put, remote: true do %> 
              <span class="fa fa-thumbs-up fa-lg white-text"></span> <span class="likes-count badge grey-gradient"><%= @post.get_upvotes.size %></span>
            <% end %>
          </div>
          </h5>
          <!-- Article -->
          <p><%= simple_format(@post.content) %> <% if can? :update, @post ||= current_user.admin %>
           <%= link_to '', edit_post_path(@post), data: {content: 'Edit', placement: 'top', trigger: 'hover'}, class: "fa fa-pencil fa-lg" %> &nbsp;
           <%= link_to '', post_path(@post), method: :delete, data: {confirm: "Are you sure?",  content: 'Delete', placement: 'top', trigger: 'hover'}, class: "fa fa-trash fa-lg" %> 
          <% end %> &nbsp; &nbsp;</p>
        </div>
         
      </section>
      <div class="section-heading">
      <%= link_to 'Comments', "#", id: "comments-link" %> <span class="badge white-text grey-gradient comments-count"><%= @post.comments.count %></span>
    </div>
      <br>
      <div id="comments">
        <%= render @comments %>
      </div>
      <!--/ Main  -->
       <hr class="between-sections wow fadeIn" data-wow-delay="0.3s" style="visibility: visible; animation-delay: 0.3s; animation-name: fadeIn;">

      <!--Section: Leave a reply (Logged In User)-->
<section class="wow fadeIn" data-wow-delay="0.3s" style="visibility: visible; animation-delay: 0.3s; animation-name: fadeIn;">
    <p class="text-center"><%= current_user.first_name.capitalize if current_user %></p>

  <!--Leave a reply form-->
  <div class="reply-form">

    <!--Third row-->
    <div class="row">
      <!--Image column-->
      <div class="col-sm-2 col-12">
        <%= gravatar_for(current_user, size: 150) if current_user %>
      </div>
      <!--/.Image column-->
  <div class="container">
    <%= form_for([@post, @post.comments.build], remote: true) do |f| %>
        <div class="md-form">
          <%= f.text_area :content, class: "md-textarea white-text" %>
        </div>
        <div class="text-center">
        <%= f.submit  class: "btn btn-outline-white btn-lg btn-rounded grey-gradient", id: "comment-btn" %>
      </div>
    <% end %>
</div>

    </div>
    <!--/.Third row-->
  </div>
  <!--/.Leave a reply form-->

</section>
<!--/Section: Leave a reply (Logged In User)-->


</div>
    </div>
    <!--/ Magazine -->
  </div>
 
  <%= link_to '', posts_path, class: "fa fa-hand-o-left fa-2x grey-text" %>

app/views/posts/vote.js.erb
<% if current_user.liked? @post %>
    $('.like-btn').addClass('liked');
<% else %>
     $('.like-btn').removeClass('liked');
<% end %>
$('.likes-count').html("<%= @post.get_upvotes.size %>")