config/routes.rb
Rails.application.routes.draw do
 mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'posts#index'
  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :galleries do
    member do
      put "like" => "galleries#vote"
    end
  end
  resources :posts do
    resources :comments
    member do
      put "like" => "posts#vote"
    end
  end
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  acts_as_votable
  belongs_to :user
  mount_uploaders :images, ImageUploader
  validate :image_size
  serialize :images#, JSON # If you use SQLite, add this line.

  private
    def image_size
      if images.size > 5.megabytes
        errors.add(:images, "Should be less than 5MB")
      end
    end
  default_scope -> { order(updated_at: :desc) }
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_gallery, only: [:show, :edit, :update, :destroy, :vote]
  before_action :authorize_admin, only: [:new]
  respond_to :js, :json, :html

  def index
    @galleries = Gallery.paginate(:page => params[:page], :per_page => 4)
  end

  def show
    @user = User.all
  end

  def new
    @gallery = Gallery.new
  end

  def edit
  end

  def create
  @gallery = Gallery.new(gallery_params)
  @gallery.user_id = current_user.id

  respond_to do |format|
    if @gallery.save
      format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
      format.json { render :show, status: :created, location: @gallery }
    else
      format.html { render :new }
      format.json { render json: @gallery.errors, status: :unprocessable_entity }
    end
  end
end

  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Gallery was successfully destroyed.' }
    end
  end

  def vote
    if !current_user.liked? @gallery
      @gallery.liked_by current_user
    elsif current_user.liked? @gallery
      @gallery.unliked_by current_user
    end
  end

  private
    def set_gallery
      @gallery = Gallery.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The image you were looking for could be found!"
      redirect_to(request.referrer || galleries_url)
    end

    def gallery_params
      params.require(:gallery).permit(:title, :user_id, :slug, {images: []})
    end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_form.html.erb
<div class="col-md-4 mx-auto">
  <div class="card grey-gradient">
    <div class="card-block">
      <div class="form-header grey-gradient">
        <i class="fa fa-camera-retro fa-2x" aria-hidden="true"></i>
      </div>
      <%= form_for @gallery, html: { multipart: true } do |f| %>
        <% if gallery.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

            <ul>
            <% gallery.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="md-form">
          <i class="fa fa-camera-retro prefix"></i>
          <%#= image_tag(@gallery.images_url) if @gallery.images? %>
          <%= f.file_field :images, multiple: true, accept: 'image/jpeg,image/jpg,image/gif,image/png' %>
          <%#= f.hidden_field :images_cache %>
        </div>

        <br>

        <div class="md-form">
          <%= f.label :title %>
          <%= f.text_field :title, autofocus: true, id: :gallery_title, class: "white-text" %>
        </div>

        <div class="md-form">
          <%= f.button 'Upload Image', class: "btn btn-block btn-lg btn-rounded grey-gradient", data: { disable_with: "<i class='fa fa-spinner fa-5x fa-spin'></i> Processing..."} %>
        </div>
      <% end %>

    </div>
  </div>
</div>

<script type="text/javascript">
  $('#image_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 10) {
      alert('Maximum file size is 10MB.');
    }
  });
</script>

app/views/galleries/edit.html.erb
<%= render 'form', gallery: @gallery %>

<%= link_to '', galleries_path, class: "fa fa-hand-o-left fa-2x faa-horizontal animated" %>

app/views/galleries/new.html.erb
<h1>New Gallery</h1>

<%= render 'form', gallery: @gallery %>

<%= link_to '', galleries_path, class: "fa fa-hand-o-left fa-2x faa-horizontal animated white-text" %>

app/views/galleries/show.html.erb
<br><br><br>
<div class="container">

  <!--Section: Blog v.4-->
  <section class="section section-blog-fw">

      <!--First row-->
      <div class="row">
          <div class="col-md-12">
              <!--Featured image-->
              <div class="view overlay hm-white-slight">
                <% @gallery.images.each_with_index do |image, index| %>
                <% if @gallery.images? %>
                  <%= image_tag image.url, class: "gallery-show" %>
                <% else %>
                    <img src="https://www.pfsuites.com/images/no_image_available.png" class="image-fluid hm-zoom" style="width: 100%;" alt="Empty Image">
                <% end %>
                  <a>
                      <div class=""></div>
                  </a>
                  <% end %>
              </div>

              <!--Post data-->
              <div class="jumbotron grey-gradient">
                  <h2><a><%= @gallery.title %></a></h2>
                  <p>Uploaded <a><%= @gallery.created_at.strftime("%B %d %Y") %></p>
                
                  <!--Social shares-->
                  <div class="social-counters ">

                      <!--Facebook-->
                      <a class="btn btn-fb ">
                          <i class="fa fa-facebook left "></i>
                          <span class="hidden-md-down ">Facebook</span>
                      </a>
                      <span class="counter ">46</span>

                      <!--Twitter-->
                      <a class="btn btn-tw ">
                          <i class="fa fa-twitter left "></i>
                          <span class="hidden-md-down ">Twitter</span>
                      </a>
                      <span class="counter ">22</span>

                      <!--Google+-->
                      <a class="btn btn-gplus ">
                          <i class="fa fa-google-plus left "></i>
                          <span class="hidden-md-down ">Google+</span>
                      </a>
                      <span class="counter ">31</span>

                      <!--Comments-->
                      <a class="btn btn-default ">
                          <i class="fa fa-comments-o left "></i>
                          <span class="hidden-md-down ">Comments</span>
                      </a>
                      <span class="counter ">18</span>

                  </div>
                  <!--/.Social shares-->

              </div>
              <!--/Post data-->

              <!--Excerpt-->
              <div class="excerpt">

              </div>
          </div>
      </div>
      <!--/First row-->

      <hr class="hr-mobile">

  </section>
  <!--/Section: Blog v.4-->

</div>

<%= link_to '', galleries_path, class: "fa fa-hand-o-left fa-2x faa-horizontal animated grey-text-gradient" %>

app/views/galleries/vote.js.erb
<% if current_user.liked? @gallery %>
    $('.like-btn').addClass('liked');
<% else %>
     $('.like-btn').removeClass('liked');
<% end %>
$('.likes-count').html("<%= @gallery.get_upvotes.size %>")